openapi: 3.0.2
info:
  version: 1.0.0
  title: SAMPLE_API

  ### 更新内容記述
  # 1. 最終更新日をDEVリリース日に設定
  # 2. * 「更新日付 API名 更新内容」の形式で記述
  # 3. 3か月以上経過している内容は削除する
  # 4. ↑ versionを更新
  description: |
    最終更新 2026年1月8日<br>
    * **2025年12月2日**：レスポンス追加
      * アバター作成API
      * アバター削除API
    * **2025年12月3日**：**ユーザー情報取得API** 追加
    * **2025年12月16日**：**ユーザー問合せ登録API**、**ユーザ更新API** 追加

tags:
  - name: PICUTURES
    description: "写真管理API"
  - name: SPRT
    description: "問合せAPI"

paths:
  "/sample/user/{user_id}":
    get:
      tags:
        - PICUTURES
      summary: "ユーザ情報取得API"
      description: >-
        ここに説明を書きます。
      parameters:
        - in: header
          name: authorization
          schema:
            type: string
          required: true
          description: "Authorizationヘッダ"
        - in: path
          name: user_id
          schema:
            type: string
          required: true
          description: "ユーザＩＤ"
          example: "XXXXXX"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                title: "srv_core_Response"
                description: "サービスコアIDレスポンス"
                type: object
                properties:
                  user_info_list:
                    description: "ユーザ情報リスト"
                    type: array
                    items:
                      type: object
                      properties:
                        user_id:
                          description: "ユーザＩＤ"
                          type: string
                          example: "XXXXXX"
                        user_name:
                          description: "ユーザ名"
                          type: string
                          example: "セコム太郎"
                        user_favorite_food:
                          description: "好きな食べ物"
                          type: string
                          example: "のどぐろ"

        "400":
          description: "不正リクエスト"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        "401":
          description: >-
            認証失敗
            <br>
            ※bodyは400と同様
        "500":
          description: >-
            サーバ内部異常
            <br>
            ※bodyは400と同様

  "/user/support":
    post:
      tags:
        - SPRT
      summary: "ユーザー問合せ登録API"
      description: >-
        ユーザー問合せ登録API
      parameters:
        - in: header
          name: authorization
          schema:
            type: string
          required: true
          description: "Authorizationヘッダ"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: "Support_Sample_Request"
              description: "問合せ内容"
              required:
                - avatar_id
                - topic
                - sub_topic
                - subject
                - body
              type: object
              properties:
                avatar_id:
                  description: "アバターID"
                  type: integer
                  example: 1
                topic:
                  description: "問合せ分類1"
                  type: string
                  example: "アプリや機器について"
                sub_topic:
                  description: "問合せ分類2"
                  type: string
                  example: "カメラについて"
                subject:
                  description: "件名"
                  type: string
                  example: "カメラの不調"
                body:
                  description: "本文"
                  type: string
                  example: "最近カメラのライブ映像が見れません。"
                camera_id:
                  description: "カメラID<br> 問合せ分類2が「カメラについて」の場合、必須"
                  type: integer
                  example: 20347
                ope_browse_flag:
                  description: "オペレーターカメラ閲覧フラグ<br>問合せ分類2が「カメラについて」の場合、必須<br> 【マッピング】0:拒否 1:許可"
                  type: integer
                  example: 1
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    description: "処理結果。0：正常終了、1：異常終了"
                    type: integer
                    example: 0
        "400":
          description: "不正リクエスト"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        "401":
          description: >-
            認証失敗
            <br>
            ※bodyは400と同様
        "500":
          description: >-
            サーバ内部異常
            <br>
            ※bodyは400と同様

  "/user/avatar":
    post:
      tags:
        - PICUTURES
      summary: "アバター作成API"
      description: ユーザー本登録後にアバター情報を作成するAPI
      parameters:
        - in: header
          name: authorization
          schema:
            type: string
          required: true
          description: "Authorizationヘッダ"
        - in: header
          name: invitation-token
          schema:
            type: string
          required: true
          description: "招待トークンヘッダ"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: "PICUTURES_Sample_Request"
              description: "アバター情報"
              required:
                - user_id
              type: object
              properties:
                user_id:
                  description: "ユーザID"
                  type: string
                  example: "XXXXXX"
                name:
                  description: "ニックネーム"
                  type: string
                  example: "アバター１"

      responses:
        "200":
          description: 正常終了
          content:
            application/json:
              schema:
                title: "avatar_Response"
                description: "アバター作成レスポンス"
                type: object
                properties:
                  avatar_id:
                    description: "アバターID"
                    type: integer
                    example: 1
        "400":
          description: "不正リクエスト"
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: integer
                    description: エラーコード
                    example: 10000
                  message:
                    type: string
                    description: エラーメッセージ
                    example: ""
        "403":
          description: "認証エラー"
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: integer
                    description: エラーコード
                  message:
                    type: string
                    description: エラーメッセージ
              examples:
                idtoken_error:
                  summary: エラーコード:30000
                  value:
                    errorCode: 30000
                    message: "認可無効"
                idtoken_decode_error:
                  summary: エラーコード:30001
                  value:
                    errorCode: 30001
                    message: "IDトークンデコード処理エラー"
                invitation_token_error:
                  summary: エラーコード:30010
                  value:
                    errorCode: 30010
                    message: "招待トークン取得エラー"
        "404":
          description: "データなし"
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: integer
                    description: エラーコード
                  message:
                    type: string
                    description: エラーメッセージ
              examples:
                invitation_data_error:
                  summary: エラーコード:40000
                  value:
                    errorCode: 40000
                    message: "招待情報取得エラー"
                camera_group_data_error:
                  summary: エラーコード:40010
                  value:
                    errorCode: 30001
                    message: "カメラグループ権限情報取得エラー"
        "500":
          description: "内部エラー"
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: integer
                    description: エラーコード
                  message:
                    type: string
                    description: エラーメッセージ
              examples:
                avatar_error:
                  summary: エラーコード:91200
                  value:
                    errorCode: 91200
                    message: "アバター作成APIエラー"
                role_error:
                  summary: エラーコード:91210
                  value:
                    errorCode: 91210
                    message: "アバター/ロール変更APIエラー"
                camera_group_error:
                  summary: エラーコード:92000
                  value:
                    errorCode: 92000
                    message: "カメラグループ権限エラー"

  "/user/{user_id}":
    put:
      tags:
        - PICUTURES
      summary: "ユーザー更新API"
      description: |
        【処理概要】を書いてみたり
      parameters:
        - in: header
          name: authorization
          schema:
            type: string
          required: true
          description: "Authorizationヘッダ"
        - in: path
          name: user_id
          schema:
            type: string
          required: true
          description: "ユーザID"
          example: "XXXXXX"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: "Update_Sample_Request"
              description: "ユーザー更新情報"
              required:
                - user_id
              type: object
              properties:
                user_type:
                  description: "ユーザ種別<br>【マッピング】<br>0:未設定、1:Authenticatorアプリ、2:電話番号"
                  type: integer
                  example: 1
                tel_no:
                  description: "電話番号<br>ユーザ種別が「2:電話番号」の場合、必須"
                  type: string
                  example: "0123456789"
                mail_address:
                  description: "メールアドレス"
                  type: string
                  example: "example@test.secom.co.jp"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        "400":
          description: "不正リクエスト"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        "401":
          description: >-
            認証失敗<br>
            ※bodyは400と同様
        "500":
          description: >-
            サーバ内部異常<br>
            ※bodyは400と同様

  "/user/avatar/{avatar_id}":
    delete:
      tags:
        - PICUTURES
      summary: "アバター削除API"
      description: アバターデータを削除するAPI
      parameters:
        - in: header
          name: authorization
          schema:
            type: string
          required: true
          description: "Authorizationヘッダ"
        - in: path
          name: avatar_id
          schema:
            type: integer
          required: true
          description: "アバターID"
          example: 1
      responses:
        "200":
          description: 正常終了
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    description: "処理結果"
                    type: integer
                    example: 0
        "400":
          description: "不正リクエスト"
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: integer
                    description: エラーコード
                    example: 11000
                  message:
                    type: string
                    description: エラーメッセージ
                    example: "パラメータ不正エラー（avatar_id）"
        "403":
          description: "認可エラー"
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: integer
                    description: エラーコード
                  message:
                    type: string
                    description: エラーメッセージ
              examples:
                cognito_error:
                  summary: エラーコード:30000
                  value:
                    errorCode: 30000
                    message: "認可無効"
                decode_error:
                  summary: エラーコード:30001
                  value:
                    errorCode: 30001
                    message: "IDトークンデコード処理エラー"
                admin_error:
                  summary: エラーコード:30010
                  value:
                    errorCode: 30001
                    message: "認可無効"
        "404":
          description: データなし
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: integer
                    description: エラーコード
                    example: 40000
                  message:
                    type: string
                    description: エラーメッセージ
                    example: "アバター情報取得エラー"
        "410":
          description: リソースなし
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: integer
                    description: エラーコード
                    example: 80000
                  message:
                    type: string
                    description: エラーメッセージ
                    example: "アバター情報削除エラー"
        "500":
          description: 内部エラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: integer
                    description: エラーコード
                  message:
                    type: string
                    description: エラーメッセージ
              examples:
                cognito_error:
                  summary: エラーコード:91200
                  value:
                    errorCode: 91200
                    message: "アバター取得APIエラー"
                decode_error:
                  summary: エラーコード:91210
                  value:
                    errorCode: 91210
                    message: "アバター削除APIエラー"

components:
  schemas:
    ApiResponse:
      description: >-
        汎用APIレスポンスオブジェクト。
        処理結果を返す。
      type: object
      properties:
        result:
          description: "処理結果。0：正常終了、1：異常終了"
          type: integer
    errorResponse:
      description: >-
        汎用APIエラーレスポンスオブジェクト。
      type: object
      properties:
        errorCode:
          description: >-
            エラーコード<br>
            10000～19999：リクエストパラメータやリクエストデータに起因するエラー<br>
            20000～29999：認証に関するエラー<br>
            30000～39999：権限に関するエラー<br>
            40000～49999：リソースの不在に関するエラー<br>
            50000～59999：メソッドの不適切な使用に関するエラー<br>
            60000～69999：タイムアウト<br>
            70000～79999：リソースの重複<br>
            80000～89999：削除済みリソース<br>
            90000～99999：内部エラー<br>
          type: integer
          example: 10000
        message:
          description: "エラーメッセージ"
          type: string
          example: "エラーメッセージ"
